Compiling 'C:\my\NOKIA\tools\2g基站割接工具\Nokia-Sbell_GSM_BTS_CUTOVER\邻区-hit\ADJ.hit' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (311) in 'C:\my\NOKIA\tools\2g基站割接工具\Nokia-Sbell_GSM_BTS_CUTOVER\邻区-hit\ADJ.h', line 319 
   Declaration of local variable 'ci' shadows global variable

** Typecheck warning (311) in 'C:\my\NOKIA\tools\2g基站割接工具\Nokia-Sbell_GSM_BTS_CUTOVER\邻区-hit\ADJ.h', line 319 
   Declaration of local variable 'lac' shadows global variable
Code generation...

Got no compile errors.

OMC: Connected
OMC: Disconnected
